# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13c24e2ff4b70c9f55c3fe4209e0684c35e079ddbe91250b950c8b2f33160e61cde36cd891f8f2a582b2051da8d19367fae4653272085db12c2e225a81927930

test:
  secret_key_base: fcdb2a15d41c52fa962aa6f8761dd1ac7fe4d53ca180950d260d72ee17040d968b3fc1e03e315b1b4494e1bc66d72427e4f0c8972cc2fbee0fb1cb74e59759e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
